// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/mesh_join/v1/mesh_join_service.proto

package mesh_joinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_openmanet_mesh_join_v1_mesh_join_service_proto protoreflect.FileDescriptor

const file_openmanet_mesh_join_v1_mesh_join_service_proto_rawDesc = "" +
	"\n" +
	".openmanet/mesh_join/v1/mesh_join_service.proto\x12\x16openmanet.mesh_join.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a&openmanet/mesh_join/v1/mesh_join.proto2\xd7\x01\n" +
	"\x0fMeshJoinService\x12V\n" +
	"\rGetMeshJoinQR\x12\x16.google.protobuf.Empty\x1a-.openmanet.mesh_join.v1.GetMeshJoinQRResponse\x12l\n" +
	"\rApplyMeshJoin\x12,.openmanet.mesh_join.v1.ApplyMeshJoinRequest\x1a-.openmanet.mesh_join.v1.ApplyMeshJoinResponseB\xf9\x01\n" +
	"\x1acom.openmanet.mesh_join.v1B\x14MeshJoinServiceProtoP\x01ZOgithub.com/openmanet/openmanetd/internal/api/openmanet/mesh_join/v1;mesh_joinv1\xa2\x02\x03OMX\xaa\x02\x15Openmanet.MeshJoin.V1\xca\x02\x15Openmanet\\MeshJoin\\V1\xe2\x02!Openmanet\\MeshJoin\\V1\\GPBMetadata\xea\x02\x17Openmanet::MeshJoin::V1b\x06proto3"

var file_openmanet_mesh_join_v1_mesh_join_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),         // 0: google.protobuf.Empty
	(*ApplyMeshJoinRequest)(nil),  // 1: openmanet.mesh_join.v1.ApplyMeshJoinRequest
	(*GetMeshJoinQRResponse)(nil), // 2: openmanet.mesh_join.v1.GetMeshJoinQRResponse
	(*ApplyMeshJoinResponse)(nil), // 3: openmanet.mesh_join.v1.ApplyMeshJoinResponse
}
var file_openmanet_mesh_join_v1_mesh_join_service_proto_depIdxs = []int32{
	0, // 0: openmanet.mesh_join.v1.MeshJoinService.GetMeshJoinQR:input_type -> google.protobuf.Empty
	1, // 1: openmanet.mesh_join.v1.MeshJoinService.ApplyMeshJoin:input_type -> openmanet.mesh_join.v1.ApplyMeshJoinRequest
	2, // 2: openmanet.mesh_join.v1.MeshJoinService.GetMeshJoinQR:output_type -> openmanet.mesh_join.v1.GetMeshJoinQRResponse
	3, // 3: openmanet.mesh_join.v1.MeshJoinService.ApplyMeshJoin:output_type -> openmanet.mesh_join.v1.ApplyMeshJoinResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openmanet_mesh_join_v1_mesh_join_service_proto_init() }
func file_openmanet_mesh_join_v1_mesh_join_service_proto_init() {
	if File_openmanet_mesh_join_v1_mesh_join_service_proto != nil {
		return
	}
	file_openmanet_mesh_join_v1_mesh_join_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_mesh_join_v1_mesh_join_service_proto_rawDesc), len(file_openmanet_mesh_join_v1_mesh_join_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openmanet_mesh_join_v1_mesh_join_service_proto_goTypes,
		DependencyIndexes: file_openmanet_mesh_join_v1_mesh_join_service_proto_depIdxs,
	}.Build()
	File_openmanet_mesh_join_v1_mesh_join_service_proto = out.File
	file_openmanet_mesh_join_v1_mesh_join_service_proto_goTypes = nil
	file_openmanet_mesh_join_v1_mesh_join_service_proto_depIdxs = nil
}
