// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: openmanet/service/v1/node.proto

package servicev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/openmanet/openmanetd/internal/api/openmanet/service/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NodeServiceName is the fully-qualified name of the NodeService service.
	NodeServiceName = "openmanet.service.v1.NodeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NodeServiceGetNodeProcedure is the fully-qualified name of the NodeService's GetNode RPC.
	NodeServiceGetNodeProcedure = "/openmanet.service.v1.NodeService/GetNode"
	// NodeServiceListNodesProcedure is the fully-qualified name of the NodeService's ListNodes RPC.
	NodeServiceListNodesProcedure = "/openmanet.service.v1.NodeService/ListNodes"
)

// NodeServiceClient is a client for the openmanet.service.v1.NodeService service.
type NodeServiceClient interface {
	// Retrieves detailed information for a specific node by hostname.
	GetNode(context.Context, *v1.GetNodeRequest) (*v1.GetNodeResponse, error)
	// Lists all nodes currently managed by the system. Rows are fed by the
	// alfred poll and expire: a peer silent for longer than alfred.nodeExpiry
	// (default 24h) is deleted on the next poll and drops out of this list.
	// No expiry runs while alfred itself is unreachable.
	ListNodes(context.Context, *emptypb.Empty) (*v1.ListNodesResponse, error)
}

// NewNodeServiceClient constructs a client for the openmanet.service.v1.NodeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNodeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NodeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nodeServiceMethods := v1.File_openmanet_service_v1_node_proto.Services().ByName("NodeService").Methods()
	return &nodeServiceClient{
		getNode: connect.NewClient[v1.GetNodeRequest, v1.GetNodeResponse](
			httpClient,
			baseURL+NodeServiceGetNodeProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("GetNode")),
			connect.WithClientOptions(opts...),
		),
		listNodes: connect.NewClient[emptypb.Empty, v1.ListNodesResponse](
			httpClient,
			baseURL+NodeServiceListNodesProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("ListNodes")),
			connect.WithClientOptions(opts...),
		),
	}
}

// nodeServiceClient implements NodeServiceClient.
type nodeServiceClient struct {
	getNode   *connect.Client[v1.GetNodeRequest, v1.GetNodeResponse]
	listNodes *connect.Client[emptypb.Empty, v1.ListNodesResponse]
}

// GetNode calls openmanet.service.v1.NodeService.GetNode.
func (c *nodeServiceClient) GetNode(ctx context.Context, req *v1.GetNodeRequest) (*v1.GetNodeResponse, error) {
	response, err := c.getNode.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListNodes calls openmanet.service.v1.NodeService.ListNodes.
func (c *nodeServiceClient) ListNodes(ctx context.Context, req *emptypb.Empty) (*v1.ListNodesResponse, error) {
	response, err := c.listNodes.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// NodeServiceHandler is an implementation of the openmanet.service.v1.NodeService service.
type NodeServiceHandler interface {
	// Retrieves detailed information for a specific node by hostname.
	GetNode(context.Context, *v1.GetNodeRequest) (*v1.GetNodeResponse, error)
	// Lists all nodes currently managed by the system. Rows are fed by the
	// alfred poll and expire: a peer silent for longer than alfred.nodeExpiry
	// (default 24h) is deleted on the next poll and drops out of this list.
	// No expiry runs while alfred itself is unreachable.
	ListNodes(context.Context, *emptypb.Empty) (*v1.ListNodesResponse, error)
}

// NewNodeServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNodeServiceHandler(svc NodeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nodeServiceMethods := v1.File_openmanet_service_v1_node_proto.Services().ByName("NodeService").Methods()
	nodeServiceGetNodeHandler := connect.NewUnaryHandlerSimple(
		NodeServiceGetNodeProcedure,
		svc.GetNode,
		connect.WithSchema(nodeServiceMethods.ByName("GetNode")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceListNodesHandler := connect.NewUnaryHandlerSimple(
		NodeServiceListNodesProcedure,
		svc.ListNodes,
		connect.WithSchema(nodeServiceMethods.ByName("ListNodes")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openmanet.service.v1.NodeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NodeServiceGetNodeProcedure:
			nodeServiceGetNodeHandler.ServeHTTP(w, r)
		case NodeServiceListNodesProcedure:
			nodeServiceListNodesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNodeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNodeServiceHandler struct{}

func (UnimplementedNodeServiceHandler) GetNode(context.Context, *v1.GetNodeRequest) (*v1.GetNodeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.service.v1.NodeService.GetNode is not implemented"))
}

func (UnimplementedNodeServiceHandler) ListNodes(context.Context, *emptypb.Empty) (*v1.ListNodesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.service.v1.NodeService.ListNodes is not implemented"))
}
