// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: openmanet/comms/v1/comms_service.proto

package commsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommsServiceClient is the client API for CommsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommsServiceClient interface {
	// Retrieves the current communications settings
	GetCommsConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCommsConfigResponse, error)
	// Updates the communication settings for the OpenMANET service.
	UpdateCommsConfig(ctx context.Context, in *UpdateCommsConfigRequest, opts ...grpc.CallOption) (*UpdateCommsConfigResponse, error)
	// Retrieves the current communication status of the OpenMANET service.
	GetCommsStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCommsStatusResponse, error)
	// Enables or disables RTP transmission on the specified talkgroup.
	SetSendTalkGroup(ctx context.Context, in *SetSendTalkGroupRequest, opts ...grpc.CallOption) (*SetSendTalkGroupResponse, error)
	// Enables or disables RTP reception on the specified talkgroup.
	SetReceiveTalkGroup(ctx context.Context, in *SetReceiveTalkGroupRequest, opts ...grpc.CallOption) (*SetReceiveTalkGroupResponse, error)
	// SelectTalkGroup makes the requested talk group the single active
	// channel: RX+TX enabled on it, all other groups disabled.
	SelectTalkGroup(ctx context.Context, in *SelectTalkGroupRequest, opts ...grpc.CallOption) (*SelectTalkGroupResponse, error)
	// StreamTalkGroupEvents streams talk group selection and direction
	// toggle changes to the client.
	StreamTalkGroupEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (CommsService_StreamTalkGroupEventsClient, error)
	// SendPTTEvent sends a PTT state change from the web client.
	SendPTTEvent(ctx context.Context, in *SendPTTEventRequest, opts ...grpc.CallOption) (*SendPTTEventResponse, error)
	// StreamAudioTx is a client-streaming RPC: the web client streams
	// Opus-encoded audio frames to the server for transmission to the mesh.
	// The server returns a summary when the client closes the stream.
	StreamAudioTx(ctx context.Context, opts ...grpc.CallOption) (CommsService_StreamAudioTxClient, error)
	// StreamAudioRx is a server-streaming RPC: the server streams
	// Opus-encoded audio frames received from the mesh back to the web client.
	StreamAudioRx(ctx context.Context, in *StreamAudioRxRequest, opts ...grpc.CallOption) (CommsService_StreamAudioRxClient, error)
	// Reads the device's hardware audio mixer state. Never fails on a
	// missing sound card — available=false is the "no card" signal.
	GetAudioMixer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAudioMixerResponse, error)
	// Applies the provided fields to the hardware mixer and persists
	// volumes and AGC so the levels survive a reboot.
	UpdateAudioMixer(ctx context.Context, in *UpdateAudioMixerRequest, opts ...grpc.CallOption) (*UpdateAudioMixerResponse, error)
}

type commsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommsServiceClient(cc grpc.ClientConnInterface) CommsServiceClient {
	return &commsServiceClient{cc}
}

func (c *commsServiceClient) GetCommsConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCommsConfigResponse, error) {
	out := new(GetCommsConfigResponse)
	err := c.cc.Invoke(ctx, "/openmanet.comms.v1.CommsService/GetCommsConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsServiceClient) UpdateCommsConfig(ctx context.Context, in *UpdateCommsConfigRequest, opts ...grpc.CallOption) (*UpdateCommsConfigResponse, error) {
	out := new(UpdateCommsConfigResponse)
	err := c.cc.Invoke(ctx, "/openmanet.comms.v1.CommsService/UpdateCommsConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsServiceClient) GetCommsStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCommsStatusResponse, error) {
	out := new(GetCommsStatusResponse)
	err := c.cc.Invoke(ctx, "/openmanet.comms.v1.CommsService/GetCommsStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsServiceClient) SetSendTalkGroup(ctx context.Context, in *SetSendTalkGroupRequest, opts ...grpc.CallOption) (*SetSendTalkGroupResponse, error) {
	out := new(SetSendTalkGroupResponse)
	err := c.cc.Invoke(ctx, "/openmanet.comms.v1.CommsService/SetSendTalkGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsServiceClient) SetReceiveTalkGroup(ctx context.Context, in *SetReceiveTalkGroupRequest, opts ...grpc.CallOption) (*SetReceiveTalkGroupResponse, error) {
	out := new(SetReceiveTalkGroupResponse)
	err := c.cc.Invoke(ctx, "/openmanet.comms.v1.CommsService/SetReceiveTalkGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsServiceClient) SelectTalkGroup(ctx context.Context, in *SelectTalkGroupRequest, opts ...grpc.CallOption) (*SelectTalkGroupResponse, error) {
	out := new(SelectTalkGroupResponse)
	err := c.cc.Invoke(ctx, "/openmanet.comms.v1.CommsService/SelectTalkGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsServiceClient) StreamTalkGroupEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (CommsService_StreamTalkGroupEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CommsService_ServiceDesc.Streams[0], "/openmanet.comms.v1.CommsService/StreamTalkGroupEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &commsServiceStreamTalkGroupEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CommsService_StreamTalkGroupEventsClient interface {
	Recv() (*StreamTalkGroupEventsResponse, error)
	grpc.ClientStream
}

type commsServiceStreamTalkGroupEventsClient struct {
	grpc.ClientStream
}

func (x *commsServiceStreamTalkGroupEventsClient) Recv() (*StreamTalkGroupEventsResponse, error) {
	m := new(StreamTalkGroupEventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *commsServiceClient) SendPTTEvent(ctx context.Context, in *SendPTTEventRequest, opts ...grpc.CallOption) (*SendPTTEventResponse, error) {
	out := new(SendPTTEventResponse)
	err := c.cc.Invoke(ctx, "/openmanet.comms.v1.CommsService/SendPTTEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsServiceClient) StreamAudioTx(ctx context.Context, opts ...grpc.CallOption) (CommsService_StreamAudioTxClient, error) {
	stream, err := c.cc.NewStream(ctx, &CommsService_ServiceDesc.Streams[1], "/openmanet.comms.v1.CommsService/StreamAudioTx", opts...)
	if err != nil {
		return nil, err
	}
	x := &commsServiceStreamAudioTxClient{stream}
	return x, nil
}

type CommsService_StreamAudioTxClient interface {
	Send(*StreamAudioTxRequest) error
	CloseAndRecv() (*StreamAudioTxResponse, error)
	grpc.ClientStream
}

type commsServiceStreamAudioTxClient struct {
	grpc.ClientStream
}

func (x *commsServiceStreamAudioTxClient) Send(m *StreamAudioTxRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *commsServiceStreamAudioTxClient) CloseAndRecv() (*StreamAudioTxResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamAudioTxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *commsServiceClient) StreamAudioRx(ctx context.Context, in *StreamAudioRxRequest, opts ...grpc.CallOption) (CommsService_StreamAudioRxClient, error) {
	stream, err := c.cc.NewStream(ctx, &CommsService_ServiceDesc.Streams[2], "/openmanet.comms.v1.CommsService/StreamAudioRx", opts...)
	if err != nil {
		return nil, err
	}
	x := &commsServiceStreamAudioRxClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CommsService_StreamAudioRxClient interface {
	Recv() (*StreamAudioRxResponse, error)
	grpc.ClientStream
}

type commsServiceStreamAudioRxClient struct {
	grpc.ClientStream
}

func (x *commsServiceStreamAudioRxClient) Recv() (*StreamAudioRxResponse, error) {
	m := new(StreamAudioRxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *commsServiceClient) GetAudioMixer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAudioMixerResponse, error) {
	out := new(GetAudioMixerResponse)
	err := c.cc.Invoke(ctx, "/openmanet.comms.v1.CommsService/GetAudioMixer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsServiceClient) UpdateAudioMixer(ctx context.Context, in *UpdateAudioMixerRequest, opts ...grpc.CallOption) (*UpdateAudioMixerResponse, error) {
	out := new(UpdateAudioMixerResponse)
	err := c.cc.Invoke(ctx, "/openmanet.comms.v1.CommsService/UpdateAudioMixer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommsServiceServer is the server API for CommsService service.
// All implementations must embed UnimplementedCommsServiceServer
// for forward compatibility
type CommsServiceServer interface {
	// Retrieves the current communications settings
	GetCommsConfig(context.Context, *emptypb.Empty) (*GetCommsConfigResponse, error)
	// Updates the communication settings for the OpenMANET service.
	UpdateCommsConfig(context.Context, *UpdateCommsConfigRequest) (*UpdateCommsConfigResponse, error)
	// Retrieves the current communication status of the OpenMANET service.
	GetCommsStatus(context.Context, *emptypb.Empty) (*GetCommsStatusResponse, error)
	// Enables or disables RTP transmission on the specified talkgroup.
	SetSendTalkGroup(context.Context, *SetSendTalkGroupRequest) (*SetSendTalkGroupResponse, error)
	// Enables or disables RTP reception on the specified talkgroup.
	SetReceiveTalkGroup(context.Context, *SetReceiveTalkGroupRequest) (*SetReceiveTalkGroupResponse, error)
	// SelectTalkGroup makes the requested talk group the single active
	// channel: RX+TX enabled on it, all other groups disabled.
	SelectTalkGroup(context.Context, *SelectTalkGroupRequest) (*SelectTalkGroupResponse, error)
	// StreamTalkGroupEvents streams talk group selection and direction
	// toggle changes to the client.
	StreamTalkGroupEvents(*emptypb.Empty, CommsService_StreamTalkGroupEventsServer) error
	// SendPTTEvent sends a PTT state change from the web client.
	SendPTTEvent(context.Context, *SendPTTEventRequest) (*SendPTTEventResponse, error)
	// StreamAudioTx is a client-streaming RPC: the web client streams
	// Opus-encoded audio frames to the server for transmission to the mesh.
	// The server returns a summary when the client closes the stream.
	StreamAudioTx(CommsService_StreamAudioTxServer) error
	// StreamAudioRx is a server-streaming RPC: the server streams
	// Opus-encoded audio frames received from the mesh back to the web client.
	StreamAudioRx(*StreamAudioRxRequest, CommsService_StreamAudioRxServer) error
	// Reads the device's hardware audio mixer state. Never fails on a
	// missing sound card — available=false is the "no card" signal.
	GetAudioMixer(context.Context, *emptypb.Empty) (*GetAudioMixerResponse, error)
	// Applies the provided fields to the hardware mixer and persists
	// volumes and AGC so the levels survive a reboot.
	UpdateAudioMixer(context.Context, *UpdateAudioMixerRequest) (*UpdateAudioMixerResponse, error)
	mustEmbedUnimplementedCommsServiceServer()
}

// UnimplementedCommsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCommsServiceServer struct {
}

func (UnimplementedCommsServiceServer) GetCommsConfig(context.Context, *emptypb.Empty) (*GetCommsConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommsConfig not implemented")
}
func (UnimplementedCommsServiceServer) UpdateCommsConfig(context.Context, *UpdateCommsConfigRequest) (*UpdateCommsConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCommsConfig not implemented")
}
func (UnimplementedCommsServiceServer) GetCommsStatus(context.Context, *emptypb.Empty) (*GetCommsStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommsStatus not implemented")
}
func (UnimplementedCommsServiceServer) SetSendTalkGroup(context.Context, *SetSendTalkGroupRequest) (*SetSendTalkGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSendTalkGroup not implemented")
}
func (UnimplementedCommsServiceServer) SetReceiveTalkGroup(context.Context, *SetReceiveTalkGroupRequest) (*SetReceiveTalkGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetReceiveTalkGroup not implemented")
}
func (UnimplementedCommsServiceServer) SelectTalkGroup(context.Context, *SelectTalkGroupRequest) (*SelectTalkGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectTalkGroup not implemented")
}
func (UnimplementedCommsServiceServer) StreamTalkGroupEvents(*emptypb.Empty, CommsService_StreamTalkGroupEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTalkGroupEvents not implemented")
}
func (UnimplementedCommsServiceServer) SendPTTEvent(context.Context, *SendPTTEventRequest) (*SendPTTEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPTTEvent not implemented")
}
func (UnimplementedCommsServiceServer) StreamAudioTx(CommsService_StreamAudioTxServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAudioTx not implemented")
}
func (UnimplementedCommsServiceServer) StreamAudioRx(*StreamAudioRxRequest, CommsService_StreamAudioRxServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAudioRx not implemented")
}
func (UnimplementedCommsServiceServer) GetAudioMixer(context.Context, *emptypb.Empty) (*GetAudioMixerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudioMixer not implemented")
}
func (UnimplementedCommsServiceServer) UpdateAudioMixer(context.Context, *UpdateAudioMixerRequest) (*UpdateAudioMixerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAudioMixer not implemented")
}
func (UnimplementedCommsServiceServer) mustEmbedUnimplementedCommsServiceServer() {}

// UnsafeCommsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommsServiceServer will
// result in compilation errors.
type UnsafeCommsServiceServer interface {
	mustEmbedUnimplementedCommsServiceServer()
}

func RegisterCommsServiceServer(s grpc.ServiceRegistrar, srv CommsServiceServer) {
	s.RegisterService(&CommsService_ServiceDesc, srv)
}

func _CommsService_GetCommsConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServiceServer).GetCommsConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.comms.v1.CommsService/GetCommsConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServiceServer).GetCommsConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommsService_UpdateCommsConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommsConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServiceServer).UpdateCommsConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.comms.v1.CommsService/UpdateCommsConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServiceServer).UpdateCommsConfig(ctx, req.(*UpdateCommsConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommsService_GetCommsStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServiceServer).GetCommsStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.comms.v1.CommsService/GetCommsStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServiceServer).GetCommsStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommsService_SetSendTalkGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSendTalkGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServiceServer).SetSendTalkGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.comms.v1.CommsService/SetSendTalkGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServiceServer).SetSendTalkGroup(ctx, req.(*SetSendTalkGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommsService_SetReceiveTalkGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReceiveTalkGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServiceServer).SetReceiveTalkGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.comms.v1.CommsService/SetReceiveTalkGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServiceServer).SetReceiveTalkGroup(ctx, req.(*SetReceiveTalkGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommsService_SelectTalkGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectTalkGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServiceServer).SelectTalkGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.comms.v1.CommsService/SelectTalkGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServiceServer).SelectTalkGroup(ctx, req.(*SelectTalkGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommsService_StreamTalkGroupEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommsServiceServer).StreamTalkGroupEvents(m, &commsServiceStreamTalkGroupEventsServer{stream})
}

type CommsService_StreamTalkGroupEventsServer interface {
	Send(*StreamTalkGroupEventsResponse) error
	grpc.ServerStream
}

type commsServiceStreamTalkGroupEventsServer struct {
	grpc.ServerStream
}

func (x *commsServiceStreamTalkGroupEventsServer) Send(m *StreamTalkGroupEventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CommsService_SendPTTEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPTTEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServiceServer).SendPTTEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.comms.v1.CommsService/SendPTTEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServiceServer).SendPTTEvent(ctx, req.(*SendPTTEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommsService_StreamAudioTx_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommsServiceServer).StreamAudioTx(&commsServiceStreamAudioTxServer{stream})
}

type CommsService_StreamAudioTxServer interface {
	SendAndClose(*StreamAudioTxResponse) error
	Recv() (*StreamAudioTxRequest, error)
	grpc.ServerStream
}

type commsServiceStreamAudioTxServer struct {
	grpc.ServerStream
}

func (x *commsServiceStreamAudioTxServer) SendAndClose(m *StreamAudioTxResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *commsServiceStreamAudioTxServer) Recv() (*StreamAudioTxRequest, error) {
	m := new(StreamAudioTxRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CommsService_StreamAudioRx_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAudioRxRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommsServiceServer).StreamAudioRx(m, &commsServiceStreamAudioRxServer{stream})
}

type CommsService_StreamAudioRxServer interface {
	Send(*StreamAudioRxResponse) error
	grpc.ServerStream
}

type commsServiceStreamAudioRxServer struct {
	grpc.ServerStream
}

func (x *commsServiceStreamAudioRxServer) Send(m *StreamAudioRxResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CommsService_GetAudioMixer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServiceServer).GetAudioMixer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.comms.v1.CommsService/GetAudioMixer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServiceServer).GetAudioMixer(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommsService_UpdateAudioMixer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAudioMixerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServiceServer).UpdateAudioMixer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openmanet.comms.v1.CommsService/UpdateAudioMixer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServiceServer).UpdateAudioMixer(ctx, req.(*UpdateAudioMixerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommsService_ServiceDesc is the grpc.ServiceDesc for CommsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openmanet.comms.v1.CommsService",
	HandlerType: (*CommsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCommsConfig",
			Handler:    _CommsService_GetCommsConfig_Handler,
		},
		{
			MethodName: "UpdateCommsConfig",
			Handler:    _CommsService_UpdateCommsConfig_Handler,
		},
		{
			MethodName: "GetCommsStatus",
			Handler:    _CommsService_GetCommsStatus_Handler,
		},
		{
			MethodName: "SetSendTalkGroup",
			Handler:    _CommsService_SetSendTalkGroup_Handler,
		},
		{
			MethodName: "SetReceiveTalkGroup",
			Handler:    _CommsService_SetReceiveTalkGroup_Handler,
		},
		{
			MethodName: "SelectTalkGroup",
			Handler:    _CommsService_SelectTalkGroup_Handler,
		},
		{
			MethodName: "SendPTTEvent",
			Handler:    _CommsService_SendPTTEvent_Handler,
		},
		{
			MethodName: "GetAudioMixer",
			Handler:    _CommsService_GetAudioMixer_Handler,
		},
		{
			MethodName: "UpdateAudioMixer",
			Handler:    _CommsService_UpdateAudioMixer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTalkGroupEvents",
			Handler:       _CommsService_StreamTalkGroupEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamAudioTx",
			Handler:       _CommsService_StreamAudioTx_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamAudioRx",
			Handler:       _CommsService_StreamAudioRx_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "openmanet/comms/v1/comms_service.proto",
}
