// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: openmanet/comms/v1/comms_service.proto

package commsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/openmanet/openmanetd/internal/api/openmanet/comms/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CommsServiceName is the fully-qualified name of the CommsService service.
	CommsServiceName = "openmanet.comms.v1.CommsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CommsServiceGetCommsConfigProcedure is the fully-qualified name of the CommsService's
	// GetCommsConfig RPC.
	CommsServiceGetCommsConfigProcedure = "/openmanet.comms.v1.CommsService/GetCommsConfig"
	// CommsServiceUpdateCommsConfigProcedure is the fully-qualified name of the CommsService's
	// UpdateCommsConfig RPC.
	CommsServiceUpdateCommsConfigProcedure = "/openmanet.comms.v1.CommsService/UpdateCommsConfig"
	// CommsServiceGetCommsStatusProcedure is the fully-qualified name of the CommsService's
	// GetCommsStatus RPC.
	CommsServiceGetCommsStatusProcedure = "/openmanet.comms.v1.CommsService/GetCommsStatus"
	// CommsServiceSetSendTalkGroupProcedure is the fully-qualified name of the CommsService's
	// SetSendTalkGroup RPC.
	CommsServiceSetSendTalkGroupProcedure = "/openmanet.comms.v1.CommsService/SetSendTalkGroup"
	// CommsServiceSetReceiveTalkGroupProcedure is the fully-qualified name of the CommsService's
	// SetReceiveTalkGroup RPC.
	CommsServiceSetReceiveTalkGroupProcedure = "/openmanet.comms.v1.CommsService/SetReceiveTalkGroup"
	// CommsServiceSelectTalkGroupProcedure is the fully-qualified name of the CommsService's
	// SelectTalkGroup RPC.
	CommsServiceSelectTalkGroupProcedure = "/openmanet.comms.v1.CommsService/SelectTalkGroup"
	// CommsServiceStreamTalkGroupEventsProcedure is the fully-qualified name of the CommsService's
	// StreamTalkGroupEvents RPC.
	CommsServiceStreamTalkGroupEventsProcedure = "/openmanet.comms.v1.CommsService/StreamTalkGroupEvents"
	// CommsServiceSendPTTEventProcedure is the fully-qualified name of the CommsService's SendPTTEvent
	// RPC.
	CommsServiceSendPTTEventProcedure = "/openmanet.comms.v1.CommsService/SendPTTEvent"
	// CommsServiceStreamAudioTxProcedure is the fully-qualified name of the CommsService's
	// StreamAudioTx RPC.
	CommsServiceStreamAudioTxProcedure = "/openmanet.comms.v1.CommsService/StreamAudioTx"
	// CommsServiceStreamAudioRxProcedure is the fully-qualified name of the CommsService's
	// StreamAudioRx RPC.
	CommsServiceStreamAudioRxProcedure = "/openmanet.comms.v1.CommsService/StreamAudioRx"
	// CommsServiceGetAudioMixerProcedure is the fully-qualified name of the CommsService's
	// GetAudioMixer RPC.
	CommsServiceGetAudioMixerProcedure = "/openmanet.comms.v1.CommsService/GetAudioMixer"
	// CommsServiceUpdateAudioMixerProcedure is the fully-qualified name of the CommsService's
	// UpdateAudioMixer RPC.
	CommsServiceUpdateAudioMixerProcedure = "/openmanet.comms.v1.CommsService/UpdateAudioMixer"
)

// CommsServiceClient is a client for the openmanet.comms.v1.CommsService service.
type CommsServiceClient interface {
	// Retrieves the current communications settings
	GetCommsConfig(context.Context, *emptypb.Empty) (*v1.GetCommsConfigResponse, error)
	// Updates the communication settings for the OpenMANET service.
	UpdateCommsConfig(context.Context, *v1.UpdateCommsConfigRequest) (*v1.UpdateCommsConfigResponse, error)
	// Retrieves the current communication status of the OpenMANET service.
	GetCommsStatus(context.Context, *emptypb.Empty) (*v1.GetCommsStatusResponse, error)
	// Enables or disables RTP transmission on the specified talkgroup.
	SetSendTalkGroup(context.Context, *v1.SetSendTalkGroupRequest) (*v1.SetSendTalkGroupResponse, error)
	// Enables or disables RTP reception on the specified talkgroup.
	SetReceiveTalkGroup(context.Context, *v1.SetReceiveTalkGroupRequest) (*v1.SetReceiveTalkGroupResponse, error)
	// SelectTalkGroup makes the requested talk group the single active
	// channel: RX+TX enabled on it, all other groups disabled.
	SelectTalkGroup(context.Context, *v1.SelectTalkGroupRequest) (*v1.SelectTalkGroupResponse, error)
	// StreamTalkGroupEvents streams talk group selection and direction
	// toggle changes to the client.
	StreamTalkGroupEvents(context.Context, *emptypb.Empty) (*connect.ServerStreamForClient[v1.StreamTalkGroupEventsResponse], error)
	// SendPTTEvent sends a PTT state change from the web client.
	SendPTTEvent(context.Context, *v1.SendPTTEventRequest) (*v1.SendPTTEventResponse, error)
	// StreamAudioTx is a client-streaming RPC: the web client streams
	// Opus-encoded audio frames to the server for transmission to the mesh.
	// The server returns a summary when the client closes the stream.
	StreamAudioTx(context.Context) (*connect.ClientStreamForClientSimple[v1.StreamAudioTxRequest, v1.StreamAudioTxResponse], error)
	// StreamAudioRx is a server-streaming RPC: the server streams
	// Opus-encoded audio frames received from the mesh back to the web client.
	StreamAudioRx(context.Context, *v1.StreamAudioRxRequest) (*connect.ServerStreamForClient[v1.StreamAudioRxResponse], error)
	// Reads the device's hardware audio mixer state. Never fails on a
	// missing sound card — available=false is the "no card" signal.
	GetAudioMixer(context.Context, *emptypb.Empty) (*v1.GetAudioMixerResponse, error)
	// Applies the provided fields to the hardware mixer and persists
	// volumes and AGC so the levels survive a reboot.
	UpdateAudioMixer(context.Context, *v1.UpdateAudioMixerRequest) (*v1.UpdateAudioMixerResponse, error)
}

// NewCommsServiceClient constructs a client for the openmanet.comms.v1.CommsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCommsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CommsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	commsServiceMethods := v1.File_openmanet_comms_v1_comms_service_proto.Services().ByName("CommsService").Methods()
	return &commsServiceClient{
		getCommsConfig: connect.NewClient[emptypb.Empty, v1.GetCommsConfigResponse](
			httpClient,
			baseURL+CommsServiceGetCommsConfigProcedure,
			connect.WithSchema(commsServiceMethods.ByName("GetCommsConfig")),
			connect.WithClientOptions(opts...),
		),
		updateCommsConfig: connect.NewClient[v1.UpdateCommsConfigRequest, v1.UpdateCommsConfigResponse](
			httpClient,
			baseURL+CommsServiceUpdateCommsConfigProcedure,
			connect.WithSchema(commsServiceMethods.ByName("UpdateCommsConfig")),
			connect.WithClientOptions(opts...),
		),
		getCommsStatus: connect.NewClient[emptypb.Empty, v1.GetCommsStatusResponse](
			httpClient,
			baseURL+CommsServiceGetCommsStatusProcedure,
			connect.WithSchema(commsServiceMethods.ByName("GetCommsStatus")),
			connect.WithClientOptions(opts...),
		),
		setSendTalkGroup: connect.NewClient[v1.SetSendTalkGroupRequest, v1.SetSendTalkGroupResponse](
			httpClient,
			baseURL+CommsServiceSetSendTalkGroupProcedure,
			connect.WithSchema(commsServiceMethods.ByName("SetSendTalkGroup")),
			connect.WithClientOptions(opts...),
		),
		setReceiveTalkGroup: connect.NewClient[v1.SetReceiveTalkGroupRequest, v1.SetReceiveTalkGroupResponse](
			httpClient,
			baseURL+CommsServiceSetReceiveTalkGroupProcedure,
			connect.WithSchema(commsServiceMethods.ByName("SetReceiveTalkGroup")),
			connect.WithClientOptions(opts...),
		),
		selectTalkGroup: connect.NewClient[v1.SelectTalkGroupRequest, v1.SelectTalkGroupResponse](
			httpClient,
			baseURL+CommsServiceSelectTalkGroupProcedure,
			connect.WithSchema(commsServiceMethods.ByName("SelectTalkGroup")),
			connect.WithClientOptions(opts...),
		),
		streamTalkGroupEvents: connect.NewClient[emptypb.Empty, v1.StreamTalkGroupEventsResponse](
			httpClient,
			baseURL+CommsServiceStreamTalkGroupEventsProcedure,
			connect.WithSchema(commsServiceMethods.ByName("StreamTalkGroupEvents")),
			connect.WithClientOptions(opts...),
		),
		sendPTTEvent: connect.NewClient[v1.SendPTTEventRequest, v1.SendPTTEventResponse](
			httpClient,
			baseURL+CommsServiceSendPTTEventProcedure,
			connect.WithSchema(commsServiceMethods.ByName("SendPTTEvent")),
			connect.WithClientOptions(opts...),
		),
		streamAudioTx: connect.NewClient[v1.StreamAudioTxRequest, v1.StreamAudioTxResponse](
			httpClient,
			baseURL+CommsServiceStreamAudioTxProcedure,
			connect.WithSchema(commsServiceMethods.ByName("StreamAudioTx")),
			connect.WithClientOptions(opts...),
		),
		streamAudioRx: connect.NewClient[v1.StreamAudioRxRequest, v1.StreamAudioRxResponse](
			httpClient,
			baseURL+CommsServiceStreamAudioRxProcedure,
			connect.WithSchema(commsServiceMethods.ByName("StreamAudioRx")),
			connect.WithClientOptions(opts...),
		),
		getAudioMixer: connect.NewClient[emptypb.Empty, v1.GetAudioMixerResponse](
			httpClient,
			baseURL+CommsServiceGetAudioMixerProcedure,
			connect.WithSchema(commsServiceMethods.ByName("GetAudioMixer")),
			connect.WithClientOptions(opts...),
		),
		updateAudioMixer: connect.NewClient[v1.UpdateAudioMixerRequest, v1.UpdateAudioMixerResponse](
			httpClient,
			baseURL+CommsServiceUpdateAudioMixerProcedure,
			connect.WithSchema(commsServiceMethods.ByName("UpdateAudioMixer")),
			connect.WithClientOptions(opts...),
		),
	}
}

// commsServiceClient implements CommsServiceClient.
type commsServiceClient struct {
	getCommsConfig        *connect.Client[emptypb.Empty, v1.GetCommsConfigResponse]
	updateCommsConfig     *connect.Client[v1.UpdateCommsConfigRequest, v1.UpdateCommsConfigResponse]
	getCommsStatus        *connect.Client[emptypb.Empty, v1.GetCommsStatusResponse]
	setSendTalkGroup      *connect.Client[v1.SetSendTalkGroupRequest, v1.SetSendTalkGroupResponse]
	setReceiveTalkGroup   *connect.Client[v1.SetReceiveTalkGroupRequest, v1.SetReceiveTalkGroupResponse]
	selectTalkGroup       *connect.Client[v1.SelectTalkGroupRequest, v1.SelectTalkGroupResponse]
	streamTalkGroupEvents *connect.Client[emptypb.Empty, v1.StreamTalkGroupEventsResponse]
	sendPTTEvent          *connect.Client[v1.SendPTTEventRequest, v1.SendPTTEventResponse]
	streamAudioTx         *connect.Client[v1.StreamAudioTxRequest, v1.StreamAudioTxResponse]
	streamAudioRx         *connect.Client[v1.StreamAudioRxRequest, v1.StreamAudioRxResponse]
	getAudioMixer         *connect.Client[emptypb.Empty, v1.GetAudioMixerResponse]
	updateAudioMixer      *connect.Client[v1.UpdateAudioMixerRequest, v1.UpdateAudioMixerResponse]
}

// GetCommsConfig calls openmanet.comms.v1.CommsService.GetCommsConfig.
func (c *commsServiceClient) GetCommsConfig(ctx context.Context, req *emptypb.Empty) (*v1.GetCommsConfigResponse, error) {
	response, err := c.getCommsConfig.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateCommsConfig calls openmanet.comms.v1.CommsService.UpdateCommsConfig.
func (c *commsServiceClient) UpdateCommsConfig(ctx context.Context, req *v1.UpdateCommsConfigRequest) (*v1.UpdateCommsConfigResponse, error) {
	response, err := c.updateCommsConfig.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetCommsStatus calls openmanet.comms.v1.CommsService.GetCommsStatus.
func (c *commsServiceClient) GetCommsStatus(ctx context.Context, req *emptypb.Empty) (*v1.GetCommsStatusResponse, error) {
	response, err := c.getCommsStatus.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SetSendTalkGroup calls openmanet.comms.v1.CommsService.SetSendTalkGroup.
func (c *commsServiceClient) SetSendTalkGroup(ctx context.Context, req *v1.SetSendTalkGroupRequest) (*v1.SetSendTalkGroupResponse, error) {
	response, err := c.setSendTalkGroup.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SetReceiveTalkGroup calls openmanet.comms.v1.CommsService.SetReceiveTalkGroup.
func (c *commsServiceClient) SetReceiveTalkGroup(ctx context.Context, req *v1.SetReceiveTalkGroupRequest) (*v1.SetReceiveTalkGroupResponse, error) {
	response, err := c.setReceiveTalkGroup.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SelectTalkGroup calls openmanet.comms.v1.CommsService.SelectTalkGroup.
func (c *commsServiceClient) SelectTalkGroup(ctx context.Context, req *v1.SelectTalkGroupRequest) (*v1.SelectTalkGroupResponse, error) {
	response, err := c.selectTalkGroup.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// StreamTalkGroupEvents calls openmanet.comms.v1.CommsService.StreamTalkGroupEvents.
func (c *commsServiceClient) StreamTalkGroupEvents(ctx context.Context, req *emptypb.Empty) (*connect.ServerStreamForClient[v1.StreamTalkGroupEventsResponse], error) {
	return c.streamTalkGroupEvents.CallServerStream(ctx, connect.NewRequest(req))
}

// SendPTTEvent calls openmanet.comms.v1.CommsService.SendPTTEvent.
func (c *commsServiceClient) SendPTTEvent(ctx context.Context, req *v1.SendPTTEventRequest) (*v1.SendPTTEventResponse, error) {
	response, err := c.sendPTTEvent.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// StreamAudioTx calls openmanet.comms.v1.CommsService.StreamAudioTx.
func (c *commsServiceClient) StreamAudioTx(ctx context.Context) (*connect.ClientStreamForClientSimple[v1.StreamAudioTxRequest, v1.StreamAudioTxResponse], error) {
	return c.streamAudioTx.CallClientStreamSimple(ctx)
}

// StreamAudioRx calls openmanet.comms.v1.CommsService.StreamAudioRx.
func (c *commsServiceClient) StreamAudioRx(ctx context.Context, req *v1.StreamAudioRxRequest) (*connect.ServerStreamForClient[v1.StreamAudioRxResponse], error) {
	return c.streamAudioRx.CallServerStream(ctx, connect.NewRequest(req))
}

// GetAudioMixer calls openmanet.comms.v1.CommsService.GetAudioMixer.
func (c *commsServiceClient) GetAudioMixer(ctx context.Context, req *emptypb.Empty) (*v1.GetAudioMixerResponse, error) {
	response, err := c.getAudioMixer.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateAudioMixer calls openmanet.comms.v1.CommsService.UpdateAudioMixer.
func (c *commsServiceClient) UpdateAudioMixer(ctx context.Context, req *v1.UpdateAudioMixerRequest) (*v1.UpdateAudioMixerResponse, error) {
	response, err := c.updateAudioMixer.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CommsServiceHandler is an implementation of the openmanet.comms.v1.CommsService service.
type CommsServiceHandler interface {
	// Retrieves the current communications settings
	GetCommsConfig(context.Context, *emptypb.Empty) (*v1.GetCommsConfigResponse, error)
	// Updates the communication settings for the OpenMANET service.
	UpdateCommsConfig(context.Context, *v1.UpdateCommsConfigRequest) (*v1.UpdateCommsConfigResponse, error)
	// Retrieves the current communication status of the OpenMANET service.
	GetCommsStatus(context.Context, *emptypb.Empty) (*v1.GetCommsStatusResponse, error)
	// Enables or disables RTP transmission on the specified talkgroup.
	SetSendTalkGroup(context.Context, *v1.SetSendTalkGroupRequest) (*v1.SetSendTalkGroupResponse, error)
	// Enables or disables RTP reception on the specified talkgroup.
	SetReceiveTalkGroup(context.Context, *v1.SetReceiveTalkGroupRequest) (*v1.SetReceiveTalkGroupResponse, error)
	// SelectTalkGroup makes the requested talk group the single active
	// channel: RX+TX enabled on it, all other groups disabled.
	SelectTalkGroup(context.Context, *v1.SelectTalkGroupRequest) (*v1.SelectTalkGroupResponse, error)
	// StreamTalkGroupEvents streams talk group selection and direction
	// toggle changes to the client.
	StreamTalkGroupEvents(context.Context, *emptypb.Empty, *connect.ServerStream[v1.StreamTalkGroupEventsResponse]) error
	// SendPTTEvent sends a PTT state change from the web client.
	SendPTTEvent(context.Context, *v1.SendPTTEventRequest) (*v1.SendPTTEventResponse, error)
	// StreamAudioTx is a client-streaming RPC: the web client streams
	// Opus-encoded audio frames to the server for transmission to the mesh.
	// The server returns a summary when the client closes the stream.
	StreamAudioTx(context.Context, *connect.ClientStream[v1.StreamAudioTxRequest]) (*v1.StreamAudioTxResponse, error)
	// StreamAudioRx is a server-streaming RPC: the server streams
	// Opus-encoded audio frames received from the mesh back to the web client.
	StreamAudioRx(context.Context, *v1.StreamAudioRxRequest, *connect.ServerStream[v1.StreamAudioRxResponse]) error
	// Reads the device's hardware audio mixer state. Never fails on a
	// missing sound card — available=false is the "no card" signal.
	GetAudioMixer(context.Context, *emptypb.Empty) (*v1.GetAudioMixerResponse, error)
	// Applies the provided fields to the hardware mixer and persists
	// volumes and AGC so the levels survive a reboot.
	UpdateAudioMixer(context.Context, *v1.UpdateAudioMixerRequest) (*v1.UpdateAudioMixerResponse, error)
}

// NewCommsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCommsServiceHandler(svc CommsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	commsServiceMethods := v1.File_openmanet_comms_v1_comms_service_proto.Services().ByName("CommsService").Methods()
	commsServiceGetCommsConfigHandler := connect.NewUnaryHandlerSimple(
		CommsServiceGetCommsConfigProcedure,
		svc.GetCommsConfig,
		connect.WithSchema(commsServiceMethods.ByName("GetCommsConfig")),
		connect.WithHandlerOptions(opts...),
	)
	commsServiceUpdateCommsConfigHandler := connect.NewUnaryHandlerSimple(
		CommsServiceUpdateCommsConfigProcedure,
		svc.UpdateCommsConfig,
		connect.WithSchema(commsServiceMethods.ByName("UpdateCommsConfig")),
		connect.WithHandlerOptions(opts...),
	)
	commsServiceGetCommsStatusHandler := connect.NewUnaryHandlerSimple(
		CommsServiceGetCommsStatusProcedure,
		svc.GetCommsStatus,
		connect.WithSchema(commsServiceMethods.ByName("GetCommsStatus")),
		connect.WithHandlerOptions(opts...),
	)
	commsServiceSetSendTalkGroupHandler := connect.NewUnaryHandlerSimple(
		CommsServiceSetSendTalkGroupProcedure,
		svc.SetSendTalkGroup,
		connect.WithSchema(commsServiceMethods.ByName("SetSendTalkGroup")),
		connect.WithHandlerOptions(opts...),
	)
	commsServiceSetReceiveTalkGroupHandler := connect.NewUnaryHandlerSimple(
		CommsServiceSetReceiveTalkGroupProcedure,
		svc.SetReceiveTalkGroup,
		connect.WithSchema(commsServiceMethods.ByName("SetReceiveTalkGroup")),
		connect.WithHandlerOptions(opts...),
	)
	commsServiceSelectTalkGroupHandler := connect.NewUnaryHandlerSimple(
		CommsServiceSelectTalkGroupProcedure,
		svc.SelectTalkGroup,
		connect.WithSchema(commsServiceMethods.ByName("SelectTalkGroup")),
		connect.WithHandlerOptions(opts...),
	)
	commsServiceStreamTalkGroupEventsHandler := connect.NewServerStreamHandlerSimple(
		CommsServiceStreamTalkGroupEventsProcedure,
		svc.StreamTalkGroupEvents,
		connect.WithSchema(commsServiceMethods.ByName("StreamTalkGroupEvents")),
		connect.WithHandlerOptions(opts...),
	)
	commsServiceSendPTTEventHandler := connect.NewUnaryHandlerSimple(
		CommsServiceSendPTTEventProcedure,
		svc.SendPTTEvent,
		connect.WithSchema(commsServiceMethods.ByName("SendPTTEvent")),
		connect.WithHandlerOptions(opts...),
	)
	commsServiceStreamAudioTxHandler := connect.NewClientStreamHandlerSimple(
		CommsServiceStreamAudioTxProcedure,
		svc.StreamAudioTx,
		connect.WithSchema(commsServiceMethods.ByName("StreamAudioTx")),
		connect.WithHandlerOptions(opts...),
	)
	commsServiceStreamAudioRxHandler := connect.NewServerStreamHandlerSimple(
		CommsServiceStreamAudioRxProcedure,
		svc.StreamAudioRx,
		connect.WithSchema(commsServiceMethods.ByName("StreamAudioRx")),
		connect.WithHandlerOptions(opts...),
	)
	commsServiceGetAudioMixerHandler := connect.NewUnaryHandlerSimple(
		CommsServiceGetAudioMixerProcedure,
		svc.GetAudioMixer,
		connect.WithSchema(commsServiceMethods.ByName("GetAudioMixer")),
		connect.WithHandlerOptions(opts...),
	)
	commsServiceUpdateAudioMixerHandler := connect.NewUnaryHandlerSimple(
		CommsServiceUpdateAudioMixerProcedure,
		svc.UpdateAudioMixer,
		connect.WithSchema(commsServiceMethods.ByName("UpdateAudioMixer")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openmanet.comms.v1.CommsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CommsServiceGetCommsConfigProcedure:
			commsServiceGetCommsConfigHandler.ServeHTTP(w, r)
		case CommsServiceUpdateCommsConfigProcedure:
			commsServiceUpdateCommsConfigHandler.ServeHTTP(w, r)
		case CommsServiceGetCommsStatusProcedure:
			commsServiceGetCommsStatusHandler.ServeHTTP(w, r)
		case CommsServiceSetSendTalkGroupProcedure:
			commsServiceSetSendTalkGroupHandler.ServeHTTP(w, r)
		case CommsServiceSetReceiveTalkGroupProcedure:
			commsServiceSetReceiveTalkGroupHandler.ServeHTTP(w, r)
		case CommsServiceSelectTalkGroupProcedure:
			commsServiceSelectTalkGroupHandler.ServeHTTP(w, r)
		case CommsServiceStreamTalkGroupEventsProcedure:
			commsServiceStreamTalkGroupEventsHandler.ServeHTTP(w, r)
		case CommsServiceSendPTTEventProcedure:
			commsServiceSendPTTEventHandler.ServeHTTP(w, r)
		case CommsServiceStreamAudioTxProcedure:
			commsServiceStreamAudioTxHandler.ServeHTTP(w, r)
		case CommsServiceStreamAudioRxProcedure:
			commsServiceStreamAudioRxHandler.ServeHTTP(w, r)
		case CommsServiceGetAudioMixerProcedure:
			commsServiceGetAudioMixerHandler.ServeHTTP(w, r)
		case CommsServiceUpdateAudioMixerProcedure:
			commsServiceUpdateAudioMixerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCommsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCommsServiceHandler struct{}

func (UnimplementedCommsServiceHandler) GetCommsConfig(context.Context, *emptypb.Empty) (*v1.GetCommsConfigResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.comms.v1.CommsService.GetCommsConfig is not implemented"))
}

func (UnimplementedCommsServiceHandler) UpdateCommsConfig(context.Context, *v1.UpdateCommsConfigRequest) (*v1.UpdateCommsConfigResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.comms.v1.CommsService.UpdateCommsConfig is not implemented"))
}

func (UnimplementedCommsServiceHandler) GetCommsStatus(context.Context, *emptypb.Empty) (*v1.GetCommsStatusResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.comms.v1.CommsService.GetCommsStatus is not implemented"))
}

func (UnimplementedCommsServiceHandler) SetSendTalkGroup(context.Context, *v1.SetSendTalkGroupRequest) (*v1.SetSendTalkGroupResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.comms.v1.CommsService.SetSendTalkGroup is not implemented"))
}

func (UnimplementedCommsServiceHandler) SetReceiveTalkGroup(context.Context, *v1.SetReceiveTalkGroupRequest) (*v1.SetReceiveTalkGroupResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.comms.v1.CommsService.SetReceiveTalkGroup is not implemented"))
}

func (UnimplementedCommsServiceHandler) SelectTalkGroup(context.Context, *v1.SelectTalkGroupRequest) (*v1.SelectTalkGroupResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.comms.v1.CommsService.SelectTalkGroup is not implemented"))
}

func (UnimplementedCommsServiceHandler) StreamTalkGroupEvents(context.Context, *emptypb.Empty, *connect.ServerStream[v1.StreamTalkGroupEventsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.comms.v1.CommsService.StreamTalkGroupEvents is not implemented"))
}

func (UnimplementedCommsServiceHandler) SendPTTEvent(context.Context, *v1.SendPTTEventRequest) (*v1.SendPTTEventResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.comms.v1.CommsService.SendPTTEvent is not implemented"))
}

func (UnimplementedCommsServiceHandler) StreamAudioTx(context.Context, *connect.ClientStream[v1.StreamAudioTxRequest]) (*v1.StreamAudioTxResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.comms.v1.CommsService.StreamAudioTx is not implemented"))
}

func (UnimplementedCommsServiceHandler) StreamAudioRx(context.Context, *v1.StreamAudioRxRequest, *connect.ServerStream[v1.StreamAudioRxResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.comms.v1.CommsService.StreamAudioRx is not implemented"))
}

func (UnimplementedCommsServiceHandler) GetAudioMixer(context.Context, *emptypb.Empty) (*v1.GetAudioMixerResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.comms.v1.CommsService.GetAudioMixer is not implemented"))
}

func (UnimplementedCommsServiceHandler) UpdateAudioMixer(context.Context, *v1.UpdateAudioMixerRequest) (*v1.UpdateAudioMixerResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.comms.v1.CommsService.UpdateAudioMixer is not implemented"))
}
