// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const createMeshNode = `-- name: CreateMeshNode :one
INSERT INTO mesh_nodes (
  mac_addr, hostname, ip_addr, latitude, longitude, altitude, uci_dhcp_start, uci_dhcp_limit, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
ON CONFLICT(mac_addr) DO UPDATE SET
  hostname = excluded.hostname,
  ip_addr = excluded.ip_addr,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  altitude = excluded.altitude,
  uci_dhcp_start = excluded.uci_dhcp_start,
  uci_dhcp_limit = excluded.uci_dhcp_limit,
  updated_at = CURRENT_TIMESTAMP
RETURNING mac_addr, hostname, ip_addr, latitude, longitude, altitude, uci_dhcp_start, uci_dhcp_limit, created_at, updated_at
`

type CreateMeshNodeParams struct {
	MacAddr      string
	Hostname     string
	IpAddr       string
	Latitude     sql.NullFloat64
	Longitude    sql.NullFloat64
	Altitude     sql.NullFloat64
	UciDhcpStart sql.NullInt64
	UciDhcpLimit sql.NullInt64
}

func (q *Queries) CreateMeshNode(ctx context.Context, arg CreateMeshNodeParams) (MeshNode, error) {
	row := q.db.QueryRowContext(ctx, createMeshNode,
		arg.MacAddr,
		arg.Hostname,
		arg.IpAddr,
		arg.Latitude,
		arg.Longitude,
		arg.Altitude,
		arg.UciDhcpStart,
		arg.UciDhcpLimit,
	)
	var i MeshNode
	err := row.Scan(
		&i.MacAddr,
		&i.Hostname,
		&i.IpAddr,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.UciDhcpStart,
		&i.UciDhcpLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllMeshNodes = `-- name: DeleteAllMeshNodes :exec
DELETE FROM mesh_nodes
`

func (q *Queries) DeleteAllMeshNodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllMeshNodes)
	return err
}

const deleteDuplicateMeshNodes = `-- name: DeleteDuplicateMeshNodes :exec
DELETE FROM mesh_nodes
WHERE rowid NOT IN (
  SELECT mn.rowid
  FROM mesh_nodes mn
  INNER JOIN (
    SELECT mac_addr, MAX(updated_at) as max_updated_at
    FROM mesh_nodes
    GROUP BY mac_addr
  ) latest ON mn.mac_addr = latest.mac_addr AND mn.updated_at = latest.max_updated_at
)
`

func (q *Queries) DeleteDuplicateMeshNodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteDuplicateMeshNodes)
	return err
}

const deleteMeshNode = `-- name: DeleteMeshNode :exec
DELETE FROM mesh_nodes
WHERE mac_addr = ?
`

func (q *Queries) DeleteMeshNode(ctx context.Context, macAddr string) error {
	_, err := q.db.ExecContext(ctx, deleteMeshNode, macAddr)
	return err
}

const deleteMeshNodesUpdatedBefore = `-- name: DeleteMeshNodesUpdatedBefore :exec
DELETE FROM mesh_nodes
WHERE updated_at < ?
`

func (q *Queries) DeleteMeshNodesUpdatedBefore(ctx context.Context, updatedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteMeshNodesUpdatedBefore, updatedAt)
	return err
}

const getMeshNode = `-- name: GetMeshNode :one
SELECT mac_addr, hostname, ip_addr, latitude, longitude, altitude, uci_dhcp_start, uci_dhcp_limit, created_at, updated_at FROM mesh_nodes
WHERE mac_addr = ? LIMIT 1
`

func (q *Queries) GetMeshNode(ctx context.Context, macAddr string) (MeshNode, error) {
	row := q.db.QueryRowContext(ctx, getMeshNode, macAddr)
	var i MeshNode
	err := row.Scan(
		&i.MacAddr,
		&i.Hostname,
		&i.IpAddr,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.UciDhcpStart,
		&i.UciDhcpLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeshNodeByHostname = `-- name: GetMeshNodeByHostname :one
SELECT mac_addr, hostname, ip_addr, latitude, longitude, altitude, uci_dhcp_start, uci_dhcp_limit, created_at, updated_at FROM mesh_nodes
WHERE hostname = ? LIMIT 1
`

func (q *Queries) GetMeshNodeByHostname(ctx context.Context, hostname string) (MeshNode, error) {
	row := q.db.QueryRowContext(ctx, getMeshNodeByHostname, hostname)
	var i MeshNode
	err := row.Scan(
		&i.MacAddr,
		&i.Hostname,
		&i.IpAddr,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.UciDhcpStart,
		&i.UciDhcpLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMeshNodes = `-- name: ListMeshNodes :many
SELECT mac_addr, hostname, ip_addr, latitude, longitude, altitude, uci_dhcp_start, uci_dhcp_limit, created_at, updated_at FROM mesh_nodes
ORDER BY hostname
`

func (q *Queries) ListMeshNodes(ctx context.Context) ([]MeshNode, error) {
	rows, err := q.db.QueryContext(ctx, listMeshNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeshNode
	for rows.Next() {
		var i MeshNode
		if err := rows.Scan(
			&i.MacAddr,
			&i.Hostname,
			&i.IpAddr,
			&i.Latitude,
			&i.Longitude,
			&i.Altitude,
			&i.UciDhcpStart,
			&i.UciDhcpLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeshNode = `-- name: UpdateMeshNode :exec
UPDATE mesh_nodes
set hostname = ?,
ip_addr = ?,
latitude = ?,
longitude = ?,
altitude = ?,
uci_dhcp_start = ?,
uci_dhcp_limit = ?,
updated_at = CURRENT_TIMESTAMP
WHERE mac_addr = ?
`

type UpdateMeshNodeParams struct {
	Hostname     string
	IpAddr       string
	Latitude     sql.NullFloat64
	Longitude    sql.NullFloat64
	Altitude     sql.NullFloat64
	UciDhcpStart sql.NullInt64
	UciDhcpLimit sql.NullInt64
	MacAddr      string
}

func (q *Queries) UpdateMeshNode(ctx context.Context, arg UpdateMeshNodeParams) error {
	_, err := q.db.ExecContext(ctx, updateMeshNode,
		arg.Hostname,
		arg.IpAddr,
		arg.Latitude,
		arg.Longitude,
		arg.Altitude,
		arg.UciDhcpStart,
		arg.UciDhcpLimit,
		arg.MacAddr,
	)
	return err
}
