// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/wifi_config/v1/wifi_config.proto

package wifi_configv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/openmanet/openmanetd/internal/api/openmanet/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WifiBand identifies the frequency band of a wireless radio.
type WifiBand int32

const (
	WifiBand_WIFI_BAND_UNSPECIFIED WifiBand = 0
	WifiBand_WIFI_BAND_2G          WifiBand = 1
	WifiBand_WIFI_BAND_5G          WifiBand = 2
	WifiBand_WIFI_BAND_6G          WifiBand = 3
	WifiBand_WIFI_BAND_S1G         WifiBand = 4
	WifiBand_WIFI_BAND_60G         WifiBand = 5
)

// Enum value maps for WifiBand.
var (
	WifiBand_name = map[int32]string{
		0: "WIFI_BAND_UNSPECIFIED",
		1: "WIFI_BAND_2G",
		2: "WIFI_BAND_5G",
		3: "WIFI_BAND_6G",
		4: "WIFI_BAND_S1G",
		5: "WIFI_BAND_60G",
	}
	WifiBand_value = map[string]int32{
		"WIFI_BAND_UNSPECIFIED": 0,
		"WIFI_BAND_2G":          1,
		"WIFI_BAND_5G":          2,
		"WIFI_BAND_6G":          3,
		"WIFI_BAND_S1G":         4,
		"WIFI_BAND_60G":         5,
	}
)

func (x WifiBand) Enum() *WifiBand {
	p := new(WifiBand)
	*p = x
	return p
}

func (x WifiBand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiBand) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_wifi_config_v1_wifi_config_proto_enumTypes[0].Descriptor()
}

func (WifiBand) Type() protoreflect.EnumType {
	return &file_openmanet_wifi_config_v1_wifi_config_proto_enumTypes[0]
}

func (x WifiBand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiBand.Descriptor instead.
func (WifiBand) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_wifi_config_v1_wifi_config_proto_rawDescGZIP(), []int{0}
}

// WifiMode identifies the operating mode of a wireless interface.
type WifiMode int32

const (
	WifiMode_WIFI_MODE_UNSPECIFIED WifiMode = 0
	WifiMode_WIFI_MODE_AP          WifiMode = 1
	WifiMode_WIFI_MODE_MESH        WifiMode = 2
	WifiMode_WIFI_MODE_STA         WifiMode = 3
	WifiMode_WIFI_MODE_ADHOC       WifiMode = 4
	WifiMode_WIFI_MODE_MONITOR     WifiMode = 5
)

// Enum value maps for WifiMode.
var (
	WifiMode_name = map[int32]string{
		0: "WIFI_MODE_UNSPECIFIED",
		1: "WIFI_MODE_AP",
		2: "WIFI_MODE_MESH",
		3: "WIFI_MODE_STA",
		4: "WIFI_MODE_ADHOC",
		5: "WIFI_MODE_MONITOR",
	}
	WifiMode_value = map[string]int32{
		"WIFI_MODE_UNSPECIFIED": 0,
		"WIFI_MODE_AP":          1,
		"WIFI_MODE_MESH":        2,
		"WIFI_MODE_STA":         3,
		"WIFI_MODE_ADHOC":       4,
		"WIFI_MODE_MONITOR":     5,
	}
)

func (x WifiMode) Enum() *WifiMode {
	p := new(WifiMode)
	*p = x
	return p
}

func (x WifiMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiMode) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_wifi_config_v1_wifi_config_proto_enumTypes[1].Descriptor()
}

func (WifiMode) Type() protoreflect.EnumType {
	return &file_openmanet_wifi_config_v1_wifi_config_proto_enumTypes[1]
}

func (x WifiMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiMode.Descriptor instead.
func (WifiMode) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_wifi_config_v1_wifi_config_proto_rawDescGZIP(), []int{1}
}

// WifiEncryption identifies the encryption method for a wireless interface.
type WifiEncryption int32

const (
	WifiEncryption_WIFI_ENCRYPTION_UNSPECIFIED WifiEncryption = 0
	WifiEncryption_WIFI_ENCRYPTION_SAE         WifiEncryption = 1
	WifiEncryption_WIFI_ENCRYPTION_PSK2        WifiEncryption = 2
	WifiEncryption_WIFI_ENCRYPTION_PSK         WifiEncryption = 3
	WifiEncryption_WIFI_ENCRYPTION_PSK_MIXED   WifiEncryption = 4
	WifiEncryption_WIFI_ENCRYPTION_NONE        WifiEncryption = 5
	WifiEncryption_WIFI_ENCRYPTION_OWE         WifiEncryption = 6
	// WPA2/WPA3 transition mode: OpenWrt maps sae-mixed to
	// auth_type=psk-sae (WPA2-PSK and WPA3-SAE both accepted). This is
	// the "WPA2/WPA3 mixed" the LuCI mesh wizard offers; psk-mixed is
	// WPA1+WPA2 and must not be labelled as WPA3.
	WifiEncryption_WIFI_ENCRYPTION_SAE_MIXED WifiEncryption = 7
)

// Enum value maps for WifiEncryption.
var (
	WifiEncryption_name = map[int32]string{
		0: "WIFI_ENCRYPTION_UNSPECIFIED",
		1: "WIFI_ENCRYPTION_SAE",
		2: "WIFI_ENCRYPTION_PSK2",
		3: "WIFI_ENCRYPTION_PSK",
		4: "WIFI_ENCRYPTION_PSK_MIXED",
		5: "WIFI_ENCRYPTION_NONE",
		6: "WIFI_ENCRYPTION_OWE",
		7: "WIFI_ENCRYPTION_SAE_MIXED",
	}
	WifiEncryption_value = map[string]int32{
		"WIFI_ENCRYPTION_UNSPECIFIED": 0,
		"WIFI_ENCRYPTION_SAE":         1,
		"WIFI_ENCRYPTION_PSK2":        2,
		"WIFI_ENCRYPTION_PSK":         3,
		"WIFI_ENCRYPTION_PSK_MIXED":   4,
		"WIFI_ENCRYPTION_NONE":        5,
		"WIFI_ENCRYPTION_OWE":         6,
		"WIFI_ENCRYPTION_SAE_MIXED":   7,
	}
)

func (x WifiEncryption) Enum() *WifiEncryption {
	p := new(WifiEncryption)
	*p = x
	return p
}

func (x WifiEncryption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiEncryption) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_wifi_config_v1_wifi_config_proto_enumTypes[2].Descriptor()
}

func (WifiEncryption) Type() protoreflect.EnumType {
	return &file_openmanet_wifi_config_v1_wifi_config_proto_enumTypes[2]
}

func (x WifiEncryption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiEncryption.Descriptor instead.
func (WifiEncryption) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_wifi_config_v1_wifi_config_proto_rawDescGZIP(), []int{2}
}

// WifiHTMode identifies the high-throughput / channel-width mode.
type WifiHTMode int32

const (
	WifiHTMode_WIFI_HT_MODE_UNSPECIFIED WifiHTMode = 0
	WifiHTMode_WIFI_HT_MODE_NOHT        WifiHTMode = 1
	WifiHTMode_WIFI_HT_MODE_HT20        WifiHTMode = 2
	WifiHTMode_WIFI_HT_MODE_HT40_MINUS  WifiHTMode = 3
	WifiHTMode_WIFI_HT_MODE_HT40_PLUS   WifiHTMode = 4
	WifiHTMode_WIFI_HT_MODE_HT40        WifiHTMode = 5
	WifiHTMode_WIFI_HT_MODE_VHT20       WifiHTMode = 6
	WifiHTMode_WIFI_HT_MODE_VHT40       WifiHTMode = 7
	WifiHTMode_WIFI_HT_MODE_VHT80       WifiHTMode = 8
	WifiHTMode_WIFI_HT_MODE_VHT160      WifiHTMode = 9
	WifiHTMode_WIFI_HT_MODE_HE20        WifiHTMode = 10
	WifiHTMode_WIFI_HT_MODE_HE40        WifiHTMode = 11
	WifiHTMode_WIFI_HT_MODE_HE80        WifiHTMode = 12
	WifiHTMode_WIFI_HT_MODE_HE160       WifiHTMode = 13
	WifiHTMode_WIFI_HT_MODE_S1G_1MHZ    WifiHTMode = 14
	WifiHTMode_WIFI_HT_MODE_S1G_2MHZ    WifiHTMode = 15
	WifiHTMode_WIFI_HT_MODE_S1G_4MHZ    WifiHTMode = 16
	WifiHTMode_WIFI_HT_MODE_S1G_8MHZ    WifiHTMode = 17
)

// Enum value maps for WifiHTMode.
var (
	WifiHTMode_name = map[int32]string{
		0:  "WIFI_HT_MODE_UNSPECIFIED",
		1:  "WIFI_HT_MODE_NOHT",
		2:  "WIFI_HT_MODE_HT20",
		3:  "WIFI_HT_MODE_HT40_MINUS",
		4:  "WIFI_HT_MODE_HT40_PLUS",
		5:  "WIFI_HT_MODE_HT40",
		6:  "WIFI_HT_MODE_VHT20",
		7:  "WIFI_HT_MODE_VHT40",
		8:  "WIFI_HT_MODE_VHT80",
		9:  "WIFI_HT_MODE_VHT160",
		10: "WIFI_HT_MODE_HE20",
		11: "WIFI_HT_MODE_HE40",
		12: "WIFI_HT_MODE_HE80",
		13: "WIFI_HT_MODE_HE160",
		14: "WIFI_HT_MODE_S1G_1MHZ",
		15: "WIFI_HT_MODE_S1G_2MHZ",
		16: "WIFI_HT_MODE_S1G_4MHZ",
		17: "WIFI_HT_MODE_S1G_8MHZ",
	}
	WifiHTMode_value = map[string]int32{
		"WIFI_HT_MODE_UNSPECIFIED": 0,
		"WIFI_HT_MODE_NOHT":        1,
		"WIFI_HT_MODE_HT20":        2,
		"WIFI_HT_MODE_HT40_MINUS":  3,
		"WIFI_HT_MODE_HT40_PLUS":   4,
		"WIFI_HT_MODE_HT40":        5,
		"WIFI_HT_MODE_VHT20":       6,
		"WIFI_HT_MODE_VHT40":       7,
		"WIFI_HT_MODE_VHT80":       8,
		"WIFI_HT_MODE_VHT160":      9,
		"WIFI_HT_MODE_HE20":        10,
		"WIFI_HT_MODE_HE40":        11,
		"WIFI_HT_MODE_HE80":        12,
		"WIFI_HT_MODE_HE160":       13,
		"WIFI_HT_MODE_S1G_1MHZ":    14,
		"WIFI_HT_MODE_S1G_2MHZ":    15,
		"WIFI_HT_MODE_S1G_4MHZ":    16,
		"WIFI_HT_MODE_S1G_8MHZ":    17,
	}
)

func (x WifiHTMode) Enum() *WifiHTMode {
	p := new(WifiHTMode)
	*p = x
	return p
}

func (x WifiHTMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiHTMode) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_wifi_config_v1_wifi_config_proto_enumTypes[3].Descriptor()
}

func (WifiHTMode) Type() protoreflect.EnumType {
	return &file_openmanet_wifi_config_v1_wifi_config_proto_enumTypes[3]
}

func (x WifiHTMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiHTMode.Descriptor instead.
func (WifiHTMode) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_wifi_config_v1_wifi_config_proto_rawDescGZIP(), []int{3}
}

// Radio identifies a physical wireless radio on the device.
type Radio struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UCI device section name, e.g. "radio2".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable label for the radio tab, e.g. "2.4 GHz Radio (MT7603E)".
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Chipset or hardware name from iwinfo, e.g. "MediaTek MT7603E".
	HardwareName string `protobuf:"bytes,3,opt,name=hardware_name,json=hardwareName,proto3" json:"hardware_name,omitempty"`
	// Frequency band of the radio.
	Band WifiBand `protobuf:"varint,4,opt,name=band,proto3,enum=openmanet.wifi_config.v1.WifiBand" json:"band,omitempty"`
	// UCI wifi-iface section name linked to this radio, e.g. "default_radio2".
	InterfaceName string `protobuf:"bytes,5,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Radio) Reset() {
	*x = Radio{}
	mi := &file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Radio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Radio) ProtoMessage() {}

func (x *Radio) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Radio.ProtoReflect.Descriptor instead.
func (*Radio) Descriptor() ([]byte, []int) {
	return file_openmanet_wifi_config_v1_wifi_config_proto_rawDescGZIP(), []int{0}
}

func (x *Radio) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Radio) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Radio) GetHardwareName() string {
	if x != nil {
		return x.HardwareName
	}
	return ""
}

func (x *Radio) GetBand() WifiBand {
	if x != nil {
		return x.Band
	}
	return WifiBand_WIFI_BAND_UNSPECIFIED
}

func (x *Radio) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

// RadioStatus contains read-only runtime information for a radio.
type RadioStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the radio is currently active.
	Active bool `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	// Current SSID being broadcast or joined.
	Ssid string `protobuf:"bytes,2,opt,name=ssid,proto3" json:"ssid,omitempty"`
	// Operating mode display string, e.g. "Access Point" or "Mesh Point (802.11s)".
	Mode string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// Current channel number.
	Channel int32 `protobuf:"varint,4,opt,name=channel,proto3" json:"channel,omitempty"`
	// Center frequency in MHz, e.g. 2412 or 923.
	Frequency int32 `protobuf:"varint,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Current bandwidth display string, e.g. "20 MHz" or "4 MHz".
	Bandwidth string `protobuf:"bytes,6,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	// Encryption display string, e.g. "WPA3-SAE" or "WPA2-PSK (CCMP)".
	Encryption string `protobuf:"bytes,7,opt,name=encryption,proto3" json:"encryption,omitempty"`
	// Current transmit power in dBm.
	TxPower int32 `protobuf:"varint,8,opt,name=tx_power,json=txPower,proto3" json:"tx_power,omitempty"`
	// Number of connected AP clients (only for AP-mode radios).
	ConnectedClients int32 `protobuf:"varint,9,opt,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	// Number of mesh peers (only for mesh-mode radios).
	MeshPeers int32 `protobuf:"varint,10,opt,name=mesh_peers,json=meshPeers,proto3" json:"mesh_peers,omitempty"`
	// Structured operating mode for programmatic use.
	WifiMode      WifiMode `protobuf:"varint,11,opt,name=wifi_mode,json=wifiMode,proto3,enum=openmanet.wifi_config.v1.WifiMode" json:"wifi_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadioStatus) Reset() {
	*x = RadioStatus{}
	mi := &file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadioStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadioStatus) ProtoMessage() {}

func (x *RadioStatus) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadioStatus.ProtoReflect.Descriptor instead.
func (*RadioStatus) Descriptor() ([]byte, []int) {
	return file_openmanet_wifi_config_v1_wifi_config_proto_rawDescGZIP(), []int{1}
}

func (x *RadioStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *RadioStatus) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *RadioStatus) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RadioStatus) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *RadioStatus) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *RadioStatus) GetBandwidth() string {
	if x != nil {
		return x.Bandwidth
	}
	return ""
}

func (x *RadioStatus) GetEncryption() string {
	if x != nil {
		return x.Encryption
	}
	return ""
}

func (x *RadioStatus) GetTxPower() int32 {
	if x != nil {
		return x.TxPower
	}
	return 0
}

func (x *RadioStatus) GetConnectedClients() int32 {
	if x != nil {
		return x.ConnectedClients
	}
	return 0
}

func (x *RadioStatus) GetMeshPeers() int32 {
	if x != nil {
		return x.MeshPeers
	}
	return 0
}

func (x *RadioStatus) GetWifiMode() WifiMode {
	if x != nil {
		return x.WifiMode
	}
	return WifiMode_WIFI_MODE_UNSPECIFIED
}

// RadioSettings contains the editable configuration for a radio.
type RadioSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SSID (network name).
	Ssid string `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	// Mesh ID (only for mesh-mode radios).
	MeshId *string `protobuf:"bytes,2,opt,name=mesh_id,json=meshId,proto3,oneof" json:"mesh_id,omitempty"`
	// Passphrase / pre-shared key. Write-only: never returned on reads.
	Password *string `protobuf:"bytes,3,opt,name=password,proto3,oneof" json:"password,omitempty"`
	// Channel number as a string (e.g. "1", "42", "auto").
	Channel string `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	// HTMode / channel-width setting.
	Bandwidth WifiHTMode `protobuf:"varint,5,opt,name=bandwidth,proto3,enum=openmanet.wifi_config.v1.WifiHTMode" json:"bandwidth,omitempty"`
	// Transmit power in dBm.
	TxPower int32 `protobuf:"varint,6,opt,name=tx_power,json=txPower,proto3" json:"tx_power,omitempty"`
	// Country code (e.g. "US").
	Country *string `protobuf:"bytes,7,opt,name=country,proto3,oneof" json:"country,omitempty"`
	// Encryption method. UNSPECIFIED means "do not change" on updates.
	Encryption WifiEncryption `protobuf:"varint,8,opt,name=encryption,proto3,enum=openmanet.wifi_config.v1.WifiEncryption" json:"encryption,omitempty"`
	// Whether the radio is disabled.
	Disabled *bool `protobuf:"varint,9,opt,name=disabled,proto3,oneof" json:"disabled,omitempty"`
	// Operating mode. UNSPECIFIED means "do not change" on updates.
	Mode WifiMode `protobuf:"varint,10,opt,name=mode,proto3,enum=openmanet.wifi_config.v1.WifiMode" json:"mode,omitempty"`
	// Peer admission floor in dBm for a mesh-mode iface: wpa_supplicant
	// refuses to peer with a station heard below it (UCI
	// mesh_rssi_threshold). The daemon writes -80 for the 2.4 GHz
	// secondary link at setup; -85 admits weaker peers in open terrain,
	// -70 drops marginal ones in dense sites. Unset on an update leaves
	// the UCI option alone; unset on a read means the option is absent or
	// the iface is not mesh.
	MeshRssiThreshold *int32 `protobuf:"varint,11,opt,name=mesh_rssi_threshold,json=meshRssiThreshold,proto3,oneof" json:"mesh_rssi_threshold,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RadioSettings) Reset() {
	*x = RadioSettings{}
	mi := &file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadioSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadioSettings) ProtoMessage() {}

func (x *RadioSettings) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadioSettings.ProtoReflect.Descriptor instead.
func (*RadioSettings) Descriptor() ([]byte, []int) {
	return file_openmanet_wifi_config_v1_wifi_config_proto_rawDescGZIP(), []int{2}
}

func (x *RadioSettings) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *RadioSettings) GetMeshId() string {
	if x != nil && x.MeshId != nil {
		return *x.MeshId
	}
	return ""
}

func (x *RadioSettings) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *RadioSettings) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RadioSettings) GetBandwidth() WifiHTMode {
	if x != nil {
		return x.Bandwidth
	}
	return WifiHTMode_WIFI_HT_MODE_UNSPECIFIED
}

func (x *RadioSettings) GetTxPower() int32 {
	if x != nil {
		return x.TxPower
	}
	return 0
}

func (x *RadioSettings) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *RadioSettings) GetEncryption() WifiEncryption {
	if x != nil {
		return x.Encryption
	}
	return WifiEncryption_WIFI_ENCRYPTION_UNSPECIFIED
}

func (x *RadioSettings) GetDisabled() bool {
	if x != nil && x.Disabled != nil {
		return *x.Disabled
	}
	return false
}

func (x *RadioSettings) GetMode() WifiMode {
	if x != nil {
		return x.Mode
	}
	return WifiMode_WIFI_MODE_UNSPECIFIED
}

func (x *RadioSettings) GetMeshRssiThreshold() int32 {
	if x != nil && x.MeshRssiThreshold != nil {
		return *x.MeshRssiThreshold
	}
	return 0
}

// ConnectedClient represents an AP-connected wireless client.
type ConnectedClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hostname resolved from DHCP leases, or empty if unknown.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// MAC address of the client.
	MacAddress string `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// Signal strength in dBm.
	SignalDbm int32 `protobuf:"varint,3,opt,name=signal_dbm,json=signalDbm,proto3" json:"signal_dbm,omitempty"`
	// Receive bitrate in bits per second.
	RxRateBps int64 `protobuf:"varint,4,opt,name=rx_rate_bps,json=rxRateBps,proto3" json:"rx_rate_bps,omitempty"`
	// Transmit bitrate in bits per second.
	TxRateBps int64 `protobuf:"varint,5,opt,name=tx_rate_bps,json=txRateBps,proto3" json:"tx_rate_bps,omitempty"`
	// Time since the client connected.
	Connected     *durationpb.Duration `protobuf:"bytes,6,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectedClient) Reset() {
	*x = ConnectedClient{}
	mi := &file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedClient) ProtoMessage() {}

func (x *ConnectedClient) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedClient.ProtoReflect.Descriptor instead.
func (*ConnectedClient) Descriptor() ([]byte, []int) {
	return file_openmanet_wifi_config_v1_wifi_config_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectedClient) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ConnectedClient) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *ConnectedClient) GetSignalDbm() int32 {
	if x != nil {
		return x.SignalDbm
	}
	return 0
}

func (x *ConnectedClient) GetRxRateBps() int64 {
	if x != nil {
		return x.RxRateBps
	}
	return 0
}

func (x *ConnectedClient) GetTxRateBps() int64 {
	if x != nil {
		return x.TxRateBps
	}
	return 0
}

func (x *ConnectedClient) GetConnected() *durationpb.Duration {
	if x != nil {
		return x.Connected
	}
	return nil
}

// MeshPeer represents a peer in a wireless mesh network.
type MeshPeer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hostname resolved from bat-hosts, or empty if unknown.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// MAC address of the peer.
	MacAddress string `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// Signal strength in dBm.
	SignalDbm int32 `protobuf:"varint,3,opt,name=signal_dbm,json=signalDbm,proto3" json:"signal_dbm,omitempty"`
	// Throughput in megabits per second.
	ThroughputMbps float64 `protobuf:"fixed64,4,opt,name=throughput_mbps,json=throughputMbps,proto3" json:"throughput_mbps,omitempty"`
	// Time since the peer was last seen.
	LastSeen      *durationpb.Duration `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshPeer) Reset() {
	*x = MeshPeer{}
	mi := &file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshPeer) ProtoMessage() {}

func (x *MeshPeer) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshPeer.ProtoReflect.Descriptor instead.
func (*MeshPeer) Descriptor() ([]byte, []int) {
	return file_openmanet_wifi_config_v1_wifi_config_proto_rawDescGZIP(), []int{4}
}

func (x *MeshPeer) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MeshPeer) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *MeshPeer) GetSignalDbm() int32 {
	if x != nil {
		return x.SignalDbm
	}
	return 0
}

func (x *MeshPeer) GetThroughputMbps() float64 {
	if x != nil {
		return x.ThroughputMbps
	}
	return 0
}

func (x *MeshPeer) GetLastSeen() *durationpb.Duration {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

var File_openmanet_wifi_config_v1_wifi_config_proto protoreflect.FileDescriptor

const file_openmanet_wifi_config_v1_wifi_config_proto_rawDesc = "" +
	"\n" +
	"*openmanet/wifi_config/v1/wifi_config.proto\x12\x18openmanet.wifi_config.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\x1a!openmanet/common/v1/options.proto\"\xc2\x01\n" +
	"\x05Radio\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12#\n" +
	"\rhardware_name\x18\x03 \x01(\tR\fhardwareName\x126\n" +
	"\x04band\x18\x04 \x01(\x0e2\".openmanet.wifi_config.v1.WifiBandR\x04band\x12%\n" +
	"\x0einterface_name\x18\x05 \x01(\tR\rinterfaceName\"\xeb\x02\n" +
	"\vRadioStatus\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x12\n" +
	"\x04ssid\x18\x02 \x01(\tR\x04ssid\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x18\n" +
	"\achannel\x18\x04 \x01(\x05R\achannel\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\x05R\tfrequency\x12\x1c\n" +
	"\tbandwidth\x18\x06 \x01(\tR\tbandwidth\x12\x1e\n" +
	"\n" +
	"encryption\x18\a \x01(\tR\n" +
	"encryption\x12\x19\n" +
	"\btx_power\x18\b \x01(\x05R\atxPower\x12+\n" +
	"\x11connected_clients\x18\t \x01(\x05R\x10connectedClients\x12\x1d\n" +
	"\n" +
	"mesh_peers\x18\n" +
	" \x01(\x05R\tmeshPeers\x12?\n" +
	"\twifi_mode\x18\v \x01(\x0e2\".openmanet.wifi_config.v1.WifiModeR\bwifiMode\"\xce\x05\n" +
	"\rRadioSettings\x12;\n" +
	"\x04ssid\x18\x01 \x01(\tB'\xbaH$r\"\x10\x01\x18 \x92\x02\topenmanet\x92\x02\x0fmy-wifi-networkR\x04ssid\x126\n" +
	"\amesh_id\x18\x02 \x01(\tB\x18\xbaH\x15r\x13\x18 \x92\x02\x0eopenmanet-meshH\x00R\x06meshId\x88\x01\x01\x12(\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x18?H\x01R\bpassword\x88\x01\x01\x122\n" +
	"\achannel\x18\x04 \x01(\tB\x18\xbaH\x15r\x13\x92\x02\x011\x92\x02\x016\x92\x02\x0236\x92\x02\x03149R\achannel\x12B\n" +
	"\tbandwidth\x18\x05 \x01(\x0e2$.openmanet.wifi_config.v1.WifiHTModeR\tbandwidth\x12*\n" +
	"\btx_power\x18\x06 \x01(\x05B\x0f\xbaH\f\x1a\n" +
	"@\n" +
	"@\x0f@\x14\x18\x1e(\x00R\atxPower\x120\n" +
	"\acountry\x18\a \x01(\tB\x11\xbaH\x0er\f\x18\x02\x92\x02\x02US\x92\x02\x02DEH\x02R\acountry\x88\x01\x01\x12H\n" +
	"\n" +
	"encryption\x18\b \x01(\x0e2(.openmanet.wifi_config.v1.WifiEncryptionR\n" +
	"encryption\x12\x1f\n" +
	"\bdisabled\x18\t \x01(\bH\x03R\bdisabled\x88\x01\x01\x126\n" +
	"\x04mode\x18\n" +
	" \x01(\x0e2\".openmanet.wifi_config.v1.WifiModeR\x04mode\x12[\n" +
	"\x13mesh_rssi_threshold\x18\v \x01(\x05B&\xbaH#\x1a!@\xb0\xff\xff\xff\xff\xff\xff\xff\xff\x01\x18\xba\xff\xff\xff\xff\xff\xff\xff\xff\x01(\xab\xff\xff\xff\xff\xff\xff\xff\xff\x01H\x04R\x11meshRssiThreshold\x88\x01\x01B\n" +
	"\n" +
	"\b_mesh_idB\v\n" +
	"\t_passwordB\n" +
	"\n" +
	"\b_countryB\v\n" +
	"\t_disabledB\x16\n" +
	"\x14_mesh_rssi_threshold\"\xe6\x01\n" +
	"\x0fConnectedClient\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"signal_dbm\x18\x03 \x01(\x05R\tsignalDbm\x12\x1e\n" +
	"\vrx_rate_bps\x18\x04 \x01(\x03R\trxRateBps\x12\x1e\n" +
	"\vtx_rate_bps\x18\x05 \x01(\x03R\ttxRateBps\x127\n" +
	"\tconnected\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\tconnected\"\xc7\x01\n" +
	"\bMeshPeer\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"signal_dbm\x18\x03 \x01(\x05R\tsignalDbm\x12'\n" +
	"\x0fthroughput_mbps\x18\x04 \x01(\x01R\x0ethroughputMbps\x126\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\blastSeen*\xb5\x01\n" +
	"\bWifiBand\x12\x19\n" +
	"\x15WIFI_BAND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\fWIFI_BAND_2G\x10\x01\x1a\b\xaa\xd1\xf9\xd6\x03\x022g\x12\x1a\n" +
	"\fWIFI_BAND_5G\x10\x02\x1a\b\xaa\xd1\xf9\xd6\x03\x025g\x12\x1a\n" +
	"\fWIFI_BAND_6G\x10\x03\x1a\b\xaa\xd1\xf9\xd6\x03\x026g\x12\x1c\n" +
	"\rWIFI_BAND_S1G\x10\x04\x1a\t\xaa\xd1\xf9\xd6\x03\x03s1g\x12\x1c\n" +
	"\rWIFI_BAND_60G\x10\x05\x1a\t\xaa\xd1\xf9\xd6\x03\x0360g*\xc7\x01\n" +
	"\bWifiMode\x12\x19\n" +
	"\x15WIFI_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\fWIFI_MODE_AP\x10\x01\x1a\b\xaa\xd1\xf9\xd6\x03\x02ap\x12\x1e\n" +
	"\x0eWIFI_MODE_MESH\x10\x02\x1a\n" +
	"\xaa\xd1\xf9\xd6\x03\x04mesh\x12\x1c\n" +
	"\rWIFI_MODE_STA\x10\x03\x1a\t\xaa\xd1\xf9\xd6\x03\x03sta\x12 \n" +
	"\x0fWIFI_MODE_ADHOC\x10\x04\x1a\v\xaa\xd1\xf9\xd6\x03\x05adhoc\x12$\n" +
	"\x11WIFI_MODE_MONITOR\x10\x05\x1a\r\xaa\xd1\xf9\xd6\x03\amonitor*\xc9\x02\n" +
	"\x0eWifiEncryption\x12\x1f\n" +
	"\x1bWIFI_ENCRYPTION_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x13WIFI_ENCRYPTION_SAE\x10\x01\x1a\t\xaa\xd1\xf9\xd6\x03\x03sae\x12$\n" +
	"\x14WIFI_ENCRYPTION_PSK2\x10\x02\x1a\n" +
	"\xaa\xd1\xf9\xd6\x03\x04psk2\x12\"\n" +
	"\x13WIFI_ENCRYPTION_PSK\x10\x03\x1a\t\xaa\xd1\xf9\xd6\x03\x03psk\x12.\n" +
	"\x19WIFI_ENCRYPTION_PSK_MIXED\x10\x04\x1a\x0f\xaa\xd1\xf9\xd6\x03\tpsk-mixed\x12$\n" +
	"\x14WIFI_ENCRYPTION_NONE\x10\x05\x1a\n" +
	"\xaa\xd1\xf9\xd6\x03\x04none\x12\"\n" +
	"\x13WIFI_ENCRYPTION_OWE\x10\x06\x1a\t\xaa\xd1\xf9\xd6\x03\x03owe\x12.\n" +
	"\x19WIFI_ENCRYPTION_SAE_MIXED\x10\a\x1a\x0f\xaa\xd1\xf9\xd6\x03\tsae-mixed*\xaa\x05\n" +
	"\n" +
	"WifiHTMode\x12\x1c\n" +
	"\x18WIFI_HT_MODE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x11WIFI_HT_MODE_NOHT\x10\x01\x1a\n" +
	"\xaa\xd1\xf9\xd6\x03\x04NOHT\x12!\n" +
	"\x11WIFI_HT_MODE_HT20\x10\x02\x1a\n" +
	"\xaa\xd1\xf9\xd6\x03\x04HT20\x12(\n" +
	"\x17WIFI_HT_MODE_HT40_MINUS\x10\x03\x1a\v\xaa\xd1\xf9\xd6\x03\x05HT40-\x12'\n" +
	"\x16WIFI_HT_MODE_HT40_PLUS\x10\x04\x1a\v\xaa\xd1\xf9\xd6\x03\x05HT40+\x12!\n" +
	"\x11WIFI_HT_MODE_HT40\x10\x05\x1a\n" +
	"\xaa\xd1\xf9\xd6\x03\x04HT40\x12#\n" +
	"\x12WIFI_HT_MODE_VHT20\x10\x06\x1a\v\xaa\xd1\xf9\xd6\x03\x05VHT20\x12#\n" +
	"\x12WIFI_HT_MODE_VHT40\x10\a\x1a\v\xaa\xd1\xf9\xd6\x03\x05VHT40\x12#\n" +
	"\x12WIFI_HT_MODE_VHT80\x10\b\x1a\v\xaa\xd1\xf9\xd6\x03\x05VHT80\x12%\n" +
	"\x13WIFI_HT_MODE_VHT160\x10\t\x1a\f\xaa\xd1\xf9\xd6\x03\x06VHT160\x12!\n" +
	"\x11WIFI_HT_MODE_HE20\x10\n" +
	"\x1a\n" +
	"\xaa\xd1\xf9\xd6\x03\x04HE20\x12!\n" +
	"\x11WIFI_HT_MODE_HE40\x10\v\x1a\n" +
	"\xaa\xd1\xf9\xd6\x03\x04HE40\x12!\n" +
	"\x11WIFI_HT_MODE_HE80\x10\f\x1a\n" +
	"\xaa\xd1\xf9\xd6\x03\x04HE80\x12#\n" +
	"\x12WIFI_HT_MODE_HE160\x10\r\x1a\v\xaa\xd1\xf9\xd6\x03\x05HE160\x12&\n" +
	"\x15WIFI_HT_MODE_S1G_1MHZ\x10\x0e\x1a\v\xaa\xd1\xf9\xd6\x03\x051 MHz\x12&\n" +
	"\x15WIFI_HT_MODE_S1G_2MHZ\x10\x0f\x1a\v\xaa\xd1\xf9\xd6\x03\x052 MHz\x12&\n" +
	"\x15WIFI_HT_MODE_S1G_4MHZ\x10\x10\x1a\v\xaa\xd1\xf9\xd6\x03\x054 MHz\x12&\n" +
	"\x15WIFI_HT_MODE_S1G_8MHZ\x10\x11\x1a\v\xaa\xd1\xf9\xd6\x03\x058 MHzB\x82\x02\n" +
	"\x1ccom.openmanet.wifi_config.v1B\x0fWifiConfigProtoP\x01ZSgithub.com/openmanet/openmanetd/internal/api/openmanet/wifi_config/v1;wifi_configv1\xa2\x02\x03OWX\xaa\x02\x17Openmanet.WifiConfig.V1\xca\x02\x17Openmanet\\WifiConfig\\V1\xe2\x02#Openmanet\\WifiConfig\\V1\\GPBMetadata\xea\x02\x19Openmanet::WifiConfig::V1b\x06proto3"

var (
	file_openmanet_wifi_config_v1_wifi_config_proto_rawDescOnce sync.Once
	file_openmanet_wifi_config_v1_wifi_config_proto_rawDescData []byte
)

func file_openmanet_wifi_config_v1_wifi_config_proto_rawDescGZIP() []byte {
	file_openmanet_wifi_config_v1_wifi_config_proto_rawDescOnce.Do(func() {
		file_openmanet_wifi_config_v1_wifi_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmanet_wifi_config_v1_wifi_config_proto_rawDesc), len(file_openmanet_wifi_config_v1_wifi_config_proto_rawDesc)))
	})
	return file_openmanet_wifi_config_v1_wifi_config_proto_rawDescData
}

var file_openmanet_wifi_config_v1_wifi_config_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_openmanet_wifi_config_v1_wifi_config_proto_goTypes = []any{
	(WifiBand)(0),               // 0: openmanet.wifi_config.v1.WifiBand
	(WifiMode)(0),               // 1: openmanet.wifi_config.v1.WifiMode
	(WifiEncryption)(0),         // 2: openmanet.wifi_config.v1.WifiEncryption
	(WifiHTMode)(0),             // 3: openmanet.wifi_config.v1.WifiHTMode
	(*Radio)(nil),               // 4: openmanet.wifi_config.v1.Radio
	(*RadioStatus)(nil),         // 5: openmanet.wifi_config.v1.RadioStatus
	(*RadioSettings)(nil),       // 6: openmanet.wifi_config.v1.RadioSettings
	(*ConnectedClient)(nil),     // 7: openmanet.wifi_config.v1.ConnectedClient
	(*MeshPeer)(nil),            // 8: openmanet.wifi_config.v1.MeshPeer
	(*durationpb.Duration)(nil), // 9: google.protobuf.Duration
}
var file_openmanet_wifi_config_v1_wifi_config_proto_depIdxs = []int32{
	0, // 0: openmanet.wifi_config.v1.Radio.band:type_name -> openmanet.wifi_config.v1.WifiBand
	1, // 1: openmanet.wifi_config.v1.RadioStatus.wifi_mode:type_name -> openmanet.wifi_config.v1.WifiMode
	3, // 2: openmanet.wifi_config.v1.RadioSettings.bandwidth:type_name -> openmanet.wifi_config.v1.WifiHTMode
	2, // 3: openmanet.wifi_config.v1.RadioSettings.encryption:type_name -> openmanet.wifi_config.v1.WifiEncryption
	1, // 4: openmanet.wifi_config.v1.RadioSettings.mode:type_name -> openmanet.wifi_config.v1.WifiMode
	9, // 5: openmanet.wifi_config.v1.ConnectedClient.connected:type_name -> google.protobuf.Duration
	9, // 6: openmanet.wifi_config.v1.MeshPeer.last_seen:type_name -> google.protobuf.Duration
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_openmanet_wifi_config_v1_wifi_config_proto_init() }
func file_openmanet_wifi_config_v1_wifi_config_proto_init() {
	if File_openmanet_wifi_config_v1_wifi_config_proto != nil {
		return
	}
	file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_wifi_config_v1_wifi_config_proto_rawDesc), len(file_openmanet_wifi_config_v1_wifi_config_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openmanet_wifi_config_v1_wifi_config_proto_goTypes,
		DependencyIndexes: file_openmanet_wifi_config_v1_wifi_config_proto_depIdxs,
		EnumInfos:         file_openmanet_wifi_config_v1_wifi_config_proto_enumTypes,
		MessageInfos:      file_openmanet_wifi_config_v1_wifi_config_proto_msgTypes,
	}.Build()
	File_openmanet_wifi_config_v1_wifi_config_proto = out.File
	file_openmanet_wifi_config_v1_wifi_config_proto_goTypes = nil
	file_openmanet_wifi_config_v1_wifi_config_proto_depIdxs = nil
}
